### PR TITLE
Actually retry on conn identification errors

### PR DESCRIPTION
**Pull request by Raynos**
We had a nice "feature" where we retried over connection
errors EXCEPT errors opening a new connection. 

This causes about 1/45 requests to fail in one of 
our production services because 1/45 hyperbahn hosts are
down.

r: @kriskowal @jcorbin @rf

cc: @blampe @prashantv Consider auditing python/go :)

cc: @MadanThangavelu This is the retry bugfix.

### CODE REVIEW

**Comment by junchaowu** [comment]
lol python seems fine. We always make sure retry on successful connections. If opening connection error exists, we automatically switch to next one until run out of peers.

**Comment by kriskowal** [comment]
Good catch. :eyes: on Travis, but otherwise :ok:

**Comment by rf** [comment]
:+1:

**Comment by jcorbin** [comment]
lgtm

**Pull request merged**
