### PR TITLE
Add an upper bound to the lifetime of a tombstone

### PR DESCRIPTION
**Pull request by Raynos**
This should upper bound the number of tombstones in a process

I think long term we really should have the Operations data
structure be a LRU or some kind of fixed size upper bounded
data structure.

This should reduce GC pressure in hyperbahn

r: @jcorbin @kriskowal @rf

### CODE REVIEW

**Comment by rf** [comment]
cool sure :+1:

**Comment by Raynos** [comment]
Test pass.

**Comment by kriskowal** [comment]
I did not overhear what the plan is to support long-lived streams.

**Comment by Raynos** [comment]
tombstones & streams are orthogonal features

**Pull request merged**
