### PR TITLE
Oops: fix lolbug

### PR DESCRIPTION
**Pull request by Raynos**
Wasn't me...

r: @blayton

### CODE REVIEW

**Comment by blampe** [comment]
Can we please add a test?

**Comment by proflayton** [comment]
https://www.youtube.com/watch?v=2g5Hz17C4is

**Comment by zhijinli** [comment]
wasn't me, but LGTM

**Comment by Raynos** [comment]
It was me :(

**Comment by Raynos** [comment]
Added regression test, will land once green. cc @blampe

**Pull request merged**
