### PR TITLE
Expose getServiceEndpoints from tchannelAsThrift

### LINKED ISSUE #249: Implement tchannelAsThrift.getEndpointNames()
@kriskowal 

TChannel 3.5.19 now depends on thriftrw 3.x which is a breaking change. As such, anybody consuming the output of `TChannelAsThrift` will break. I believe this should justify a major version bump.

### PR DESCRIPTION
**Pull request by Willyham**
@kriskowal Fixes #249 

Depends on https://github.com/uber/thriftrw-node/pull/101

### CODE REVIEW

**Comment by Raynos** [comment]
lgtm.

**Comment by kriskowal** [comment]
We will need to roll the implementation of getServiceEndpoints into ThriftRW or implement it here instead.

**Comment by kriskowal** [comment]
Looked deeper. Thanks—we will need to roll a release and uprev this branch to land.

**Comment by kriskowal** [comment]
I’ve pushed a commit to uprev thriftrw. Standing by.

**Pull request merged**
