### PR TITLE
Peer: cache score ranges

### PR DESCRIPTION
**Pull request by rf**
r @jcorbin @Raynos 

Caches ranges on the peer object.
Ranges, no caching: https://people.uberinternal.com/~rf/ranges.svg
cached: https://people.uberinternal.com/~rf/range-cache.svg

### CODE REVIEW

**Comment by blampe** [comment]
Is distribution still even with this?

**Comment by rf** [comment]
Yes -- this caches the possible range from which we choose randomly; we don't cache the randomness.

**Comment by jcorbin** [comment]
lgtm

**Comment by jcorbin** [comment]
Even better, :100:

**Pull request merged**
